# Retrieving Data From a Single Table
we use Pandas to import data from mysql and then execute SQL query

In [2]:
import os
from dotenv import load_dotenv

import pandas as pd
import sqlalchemy

In [3]:
load_dotenv()

db_host = os.environ.get("db_host")
db_user = os.environ.get("db_user")
db_password = os.environ.get("db_password")

In [4]:
engine = sqlalchemy.create_engine(f"mysql+pymysql://{db_user}:{db_password}@{db_host}:3306/sql_store")

### The SELECT Statement

In [5]:
df = pd.read_sql("SELECT * FROM customers", con=engine)
df

,customer_id,first_name,last_name,birth_date,phone,address,city,state,points
0,1,Babara,MacCaffrey,1986-03-28,781-932-9754,0 Sage Terrace,Waltham,VA,2273
1,2,Ines,Brushfield,1986-04-13,804-427-9456,14187 Commercial Trail,Hampton,VA,947
2,3,Freddi,Boagey,1985-02-07,719-724-7869,251 Springs Junction,Colorado Springs,CO,2967
3,4,Ambur,Roseburgh,1974-04-14,407-231-8017,30 Arapahoe Terrace,Orlando,FL,457
4,5,Clemmie,Betchley,1973-11-07,None,5 Spohn Circle,Arlington,TX,3675
5,6,Elka,Twiddell,1991-09-04,312-480-8498,7 Manley Drive,Chicago,IL,3073
6,7,Ilene,Dowson,1964-08-30,615-641-4759,50 Lillian Crossing,Nashville,TN,1672
7,8,Thacher,Naseby,1993-07-17,941-527-3977,538 Mosinee Center,Sarasota,FL,205
8,9,Romola,Rumgay,1992-05-23,559-181-3744,3520 Ohio Trail,Visalia,CA,1486
9,10,Levy,Mynett,1969-10-13,404-246-3370,68 Lawn Avenue,Atlanta,GA,796

In [6]:
query = """
select *
from customers
where customer_id > 5 
order by first_name
"""


pd.read_sql(query, con= engine)

,customer_id,first_name,last_name,birth_date,phone,address,city,state,points
0,6,Elka,Twiddell,1991-09-04,312-480-8498,7 Manley Drive,Chicago,IL,3073
1,7,Ilene,Dowson,1964-08-30,615-641-4759,50 Lillian Crossing,Nashville,TN,1672
2,10,Levy,Mynett,1969-10-13,404-246-3370,68 Lawn Avenue,Atlanta,GA,796
3,9,Romola,Rumgay,1992-05-23,559-181-3744,3520 Ohio Trail,Visalia,CA,1486
4,8,Thacher,Naseby,1993-07-17,941-527-3977,538 Mosinee Center,Sarasota,FL,205

In [7]:
query = """
select 
    last_name,
    first_name,
    concat(first_name, " ", last_name) as full_name
from customers
"""


pd.read_sql(query, con= engine)

    last_name first_name          full_name
0  MacCaffrey     Babara  Babara MacCaffrey
1  Brushfield       Ines    Ines Brushfield
2      Boagey     Freddi      Freddi Boagey
3   Roseburgh      Ambur    Ambur Roseburgh
4    Betchley    Clemmie   Clemmie Betchley
5    Twiddell       Elka      Elka Twiddell
6      Dowson      Ilene       Ilene Dowson
7      Naseby    Thacher     Thacher Naseby
8      Rumgay     Romola      Romola Rumgay
9      Mynett       Levy        Levy Mynett

### DISTINCT

we use `DISTINCT` key word to select unique values from a table:

In [8]:
query = """
select distinct state 
from customers
"""


pd.read_sql(query, con= engine)

  state
0    VA
1    CO
2    FL
3    TX
4    IL
5    TN
6    CA
7    GA

EXERCISE:

In [9]:
query = """
select 
    name,
    unit_price,
    unit_price * 1.1 as "new price"
from products
"""


pd.read_sql(query, con= engine)

                           name  unit_price  new price
0             Foam Dinner Plate        1.21      1.331
1     Pork - Bacon,back Peameal        4.65      5.115
2      Lettuce - Romaine, Heart        3.35      3.685
3  Brocolinni - Gaylan, Chinese        4.53      4.983
4        Sauce - Ranch Dressing        1.63      1.793
5                Petit Baguette        2.39      2.629
6             Sweet Pea Sprouts        3.29      3.619
7      Island Oasis - Raspberry        0.74      0.814
8                        Longan        2.26      2.486
9                  Broom - Push        1.09      1.199

### WHERE Clause

Comparison Operators:
<, >, <=, >=, =, !=

In [10]:
query = """
select *
from customers
where state = "va"
"""


pd.read_sql(query, con= engine)

,customer_id,first_name,last_name,birth_date,phone,address,city,state,points
0,1,Babara,MacCaffrey,1986-03-28,781-932-9754,0 Sage Terrace,Waltham,VA,2273
1,2,Ines,Brushfield,1986-04-13,804-427-9456,14187 Commercial Trail,Hampton,VA,947

EXERCISE:

In [11]:
query = """
select *
from orders
where order_date >= "2019-01-01"
"""


pd.read_sql(query, con= engine)

   order_id  customer_id  order_date  status comments shipped_date shipper_id
0         1            6  2019-01-30       1     None         None       None

### AND, OR, NOT Operators

In [12]:
query = """
select *
from customers
where (birth_date > "1990-01-01" and not points > 1000) or (points > 3000)
"""


pd.read_sql(query, con= engine)

,customer_id,first_name,last_name,birth_date,phone,address,city,state,points
0,5,Clemmie,Betchley,1973-11-07,None,5 Spohn Circle,Arlington,TX,3675
1,6,Elka,Twiddell,1991-09-04,312-480-8498,7 Manley Drive,Chicago,IL,3073
2,8,Thacher,Naseby,1993-07-17,941-527-3977,538 Mosinee Center,Sarasota,FL,205

EXERCIS:

In [13]:
query = """
select *
from order_items
where order_id = 6 and (quantity * unit_price > 30)
"""


pd.read_sql(query, con= engine)

   order_id  product_id  quantity  unit_price
0         6           1         4        8.65

### IN Operator

In [14]:
query = """
select *
from customers
where state in ("VA", "FL", "GA")
-- where state = "VA" or state = "FL" or state = "GA" 
"""


pd.read_sql(query, con= engine)

,customer_id,first_name,last_name,birth_date,phone,address,city,state,points
0,1,Babara,MacCaffrey,1986-03-28,781-932-9754,0 Sage Terrace,Waltham,VA,2273
1,2,Ines,Brushfield,1986-04-13,804-427-9456,14187 Commercial Trail,Hampton,VA,947
2,4,Ambur,Roseburgh,1974-04-14,407-231-8017,30 Arapahoe Terrace,Orlando,FL,457
3,8,Thacher,Naseby,1993-07-17,941-527-3977,538 Mosinee Center,Sarasota,FL,205
4,10,Levy,Mynett,1969-10-13,404-246-3370,68 Lawn Avenue,Atlanta,GA,796

EXERCISE:

In [15]:
query = """
select *
from products
where quantity_in_stock in (49, 38, 72)
"""


pd.read_sql(query, con= engine)

   product_id                       name  quantity_in_stock  unit_price
0           2  Pork - Bacon,back Peameal                 49        4.65
1           3   Lettuce - Romaine, Heart                 38        3.35

### BETWEEN Operator

In [16]:
query = """
select *
from customers
where points between 1000 and 3000
-- where points >= 1000 and points <= 3000
"""


pd.read_sql(query, con= engine)

,customer_id,first_name,last_name,birth_date,phone,address,city,state,points
0,1,Babara,MacCaffrey,1986-03-28,781-932-9754,0 Sage Terrace,Waltham,VA,2273
1,3,Freddi,Boagey,1985-02-07,719-724-7869,251 Springs Junction,Colorado Springs,CO,2967
2,7,Ilene,Dowson,1964-08-30,615-641-4759,50 Lillian Crossing,Nashville,TN,1672
3,9,Romola,Rumgay,1992-05-23,559-181-3744,3520 Ohio Trail,Visalia,CA,1486

EXERCISE:

In [17]:
query = """
select *
from customers
where birth_date between "1990-01-01" and "2000-01-01"
"""


pd.read_sql(query, con= engine)

,customer_id,first_name,last_name,birth_date,phone,address,city,state,points
0,6,Elka,Twiddell,1991-09-04,312-480-8498,7 Manley Drive,Chicago,IL,3073
1,8,Thacher,Naseby,1993-07-17,941-527-3977,538 Mosinee Center,Sarasota,FL,205
2,9,Romola,Rumgay,1992-05-23,559-181-3744,3520 Ohio Trail,Visalia,CA,1486

### LIKE Operator

`%` : any number of characters

`_` : single character

In [18]:
query = """
select *
from customers
where last_name like "_b" 
"""


pd.read_sql(query, con= engine)

Empty DataFrame
Columns: [customer_id, first_name, last_name, birth_date, phone, address, city, state, points]
Index: []

### IS NULL Operator

In [19]:
query = """
select *
from customers
where phone is null 
"""


pd.read_sql(query, con= engine)

,customer_id,first_name,last_name,birth_date,phone,address,city,state,points
0,5,Clemmie,Betchley,1973-11-07,None,5 Spohn Circle,Arlington,TX,3675

In [20]:
query = """
select *
from customers
where phone is not null 
"""


pd.read_sql(query, con= engine)

,customer_id,first_name,last_name,birth_date,phone,address,city,state,points
0,1,Babara,MacCaffrey,1986-03-28,781-932-9754,0 Sage Terrace,Waltham,VA,2273
1,2,Ines,Brushfield,1986-04-13,804-427-9456,14187 Commercial Trail,Hampton,VA,947
2,3,Freddi,Boagey,1985-02-07,719-724-7869,251 Springs Junction,Colorado Springs,CO,2967
3,4,Ambur,Roseburgh,1974-04-14,407-231-8017,30 Arapahoe Terrace,Orlando,FL,457
4,6,Elka,Twiddell,1991-09-04,312-480-8498,7 Manley Drive,Chicago,IL,3073
5,7,Ilene,Dowson,1964-08-30,615-641-4759,50 Lillian Crossing,Nashville,TN,1672
6,8,Thacher,Naseby,1993-07-17,941-527-3977,538 Mosinee Center,Sarasota,FL,205
7,9,Romola,Rumgay,1992-05-23,559-181-3744,3520 Ohio Trail,Visalia,CA,1486
8,10,Levy,Mynett,1969-10-13,404-246-3370,68 Lawn Avenue,Atlanta,GA,796

### ORDER BY Operator

In [21]:
query = """
select *
from customers
order by state, first_name 
"""


pd.read_sql(query, con= engine)

,customer_id,first_name,last_name,birth_date,phone,address,city,state,points
0,9,Romola,Rumgay,1992-05-23,559-181-3744,3520 Ohio Trail,Visalia,CA,1486
1,3,Freddi,Boagey,1985-02-07,719-724-7869,251 Springs Junction,Colorado Springs,CO,2967
2,4,Ambur,Roseburgh,1974-04-14,407-231-8017,30 Arapahoe Terrace,Orlando,FL,457
3,8,Thacher,Naseby,1993-07-17,941-527-3977,538 Mosinee Center,Sarasota,FL,205
4,10,Levy,Mynett,1969-10-13,404-246-3370,68 Lawn Avenue,Atlanta,GA,796
5,6,Elka,Twiddell,1991-09-04,312-480-8498,7 Manley Drive,Chicago,IL,3073
6,7,Ilene,Dowson,1964-08-30,615-641-4759,50 Lillian Crossing,Nashville,TN,1672
7,5,Clemmie,Betchley,1973-11-07,None,5 Spohn Circle,Arlington,TX,3675
8,1,Babara,MacCaffrey,1986-03-28,781-932-9754,0 Sage Terrace,Waltham,VA,2273
9,2,Ines,Brushfield,1986-04-13,804-427-9456,14187 Commercial Trail,Hampton,VA,947

we use `DESC` keyword to reverse the sort order:

In [22]:
query = """
select *
from customers
order by first_name desc
"""


pd.read_sql(query, con= engine)

,customer_id,first_name,last_name,birth_date,phone,address,city,state,points
0,8,Thacher,Naseby,1993-07-17,941-527-3977,538 Mosinee Center,Sarasota,FL,205
1,9,Romola,Rumgay,1992-05-23,559-181-3744,3520 Ohio Trail,Visalia,CA,1486
2,10,Levy,Mynett,1969-10-13,404-246-3370,68 Lawn Avenue,Atlanta,GA,796
3,2,Ines,Brushfield,1986-04-13,804-427-9456,14187 Commercial Trail,Hampton,VA,947
4,7,Ilene,Dowson,1964-08-30,615-641-4759,50 Lillian Crossing,Nashville,TN,1672
5,3,Freddi,Boagey,1985-02-07,719-724-7869,251 Springs Junction,Colorado Springs,CO,2967
6,6,Elka,Twiddell,1991-09-04,312-480-8498,7 Manley Drive,Chicago,IL,3073
7,5,Clemmie,Betchley,1973-11-07,None,5 Spohn Circle,Arlington,TX,3675
8,1,Babara,MacCaffrey,1986-03-28,781-932-9754,0 Sage Terrace,Waltham,VA,2273
9,4,Ambur,Roseburgh,1974-04-14,407-231-8017,30 Arapahoe Terrace,Orlando,FL,457

EXERCISE:

In [23]:
query = """
select *
from order_items
where order_id = 2
order by (quantity * unit_price) desc
"""


pd.read_sql(query, con= engine)

   order_id  product_id  quantity  unit_price
0         2           1         2        9.10
1         2           4         4        1.66
2         2           6         2        2.94

### LIMIT Clause

In [24]:
query = """
select *
from customers
limit 3
"""


pd.read_sql(query, con= engine)

,customer_id,first_name,last_name,birth_date,phone,address,city,state,points
0,1,Babara,MacCaffrey,1986-03-28,781-932-9754,0 Sage Terrace,Waltham,VA,2273
1,2,Ines,Brushfield,1986-04-13,804-427-9456,14187 Commercial Trail,Hampton,VA,947
2,3,Freddi,Boagey,1985-02-07,719-724-7869,251 Springs Junction,Colorado Springs,CO,2967

In [25]:
query = """
select *
from customers
limit 6, 3      -- it means that skip the first 6 records and then pick 3 records 
"""


pd.read_sql(query, con= engine)

,customer_id,first_name,last_name,birth_date,phone,address,city,state,points
0,7,Ilene,Dowson,1964-08-30,615-641-4759,50 Lillian Crossing,Nashville,TN,1672
1,8,Thacher,Naseby,1993-07-17,941-527-3977,538 Mosinee Center,Sarasota,FL,205
2,9,Romola,Rumgay,1992-05-23,559-181-3744,3520 Ohio Trail,Visalia,CA,1486