# Retrieving Data From Multiple Tables

In [26]:
import os
from dotenv import load_dotenv

import pandas as pd
import sqlalchemy

In [27]:
load_dotenv()

db_host = os.environ.get("db_host")
db_user = os.environ.get("db_user")
db_password = os.environ.get("db_password")

In [28]:
engine = sqlalchemy.create_engine(f"mysql+pymysql://{db_user}:{db_password}@{db_host}:3306/sql_store")

In [29]:
pd.read_sql("show tables", con = engine)

  Tables_in_sql_store
0           customers
1    order_item_notes
2         order_items
3      order_statuses
4              orders
5            products
6            shippers

## Inner Joins
We use `ON` to define a specific condition and say: show the row from the second table next to the row from the first table where that condition holds; otherwise, for each row of the main table, it shows all rows of the second table.

In [30]:
query = """
select *
from orders
join customers
"""

pd.read_sql(query, con = engine)

,order_id,customer_id,order_date,status,comments,shipped_date,shipper_id,customer_id,first_name,last_name,birth_date,phone,address,city,state,points
0,10,6,2018-04-22,2,None,2018-04-23,2.0,1,Babara,MacCaffrey,1986-03-28,781-932-9754,0 Sage Terrace,Waltham,VA,2273
1,9,10,2017-07-05,2,Nulla mollis molestie lorem. Quisque ut erat.,2017-07-06,1.0,1,Babara,MacCaffrey,1986-03-28,781-932-9754,0 Sage Terrace,Waltham,VA,2273
2,8,5,2018-06-08,1,"Mauris enim leo, rhoncus sed, vestibulum sit a...",None,NaN,1,Babara,MacCaffrey,1986-03-28,781-932-9754,0 Sage Terrace,Waltham,VA,2273
3,7,2,2018-09-22,2,None,2018-09-23,4.0,1,Babara,MacCaffrey,1986-03-28,781-932-9754,0 Sage Terrace,Waltham,VA,2273
4,6,10,2018-11-18,1,Aliquam erat volutpat. In congue.,None,NaN,1,Babara,MacCaffrey,1986-03-28,781-932-9754,0 Sage Terrace,Waltham,VA,2273
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,5,5,2017-08-25,2,,2017-08-26,3.0,10,Levy,Mynett,1969-10-13,404-246-3370,68 Lawn Avenue,Atlanta,GA,796
96,4,2,2017-01-22,1,None,None,NaN,10,Levy,Mynett,1969-10-13,404-246-3370,68 Lawn Avenue,Atlanta,GA,796
97,3,8,2017-12-01,1,None,None,NaN,10,Levy,Mynett,1969-10-13,404-246-3370,68 Lawn Avenue,Atlanta,GA,796
98,2,7,2018-08-02,2,None,2018-08-03,4.0,10,Levy,Mynett,1969-10-13,404-246-3370,68 Lawn Avenue,Atlanta,GA,796
99,1,6,2019-01-30,1,None,None,NaN,10,Levy,Mynett,1969-10-13,404-246-3370,68 Lawn Avenue,Atlanta,GA,796

In [31]:
query = """
select *
from orders
join customers on orders.customer_id = customers.customer_id
"""

pd.read_sql(query, con = engine)

,order_id,customer_id,order_date,status,comments,shipped_date,shipper_id,customer_id,first_name,last_name,birth_date,phone,address,city,state,points
0,1,6,2019-01-30,1,None,None,NaN,6,Elka,Twiddell,1991-09-04,312-480-8498,7 Manley Drive,Chicago,IL,3073
1,2,7,2018-08-02,2,None,2018-08-03,4.0,7,Ilene,Dowson,1964-08-30,615-641-4759,50 Lillian Crossing,Nashville,TN,1672
2,3,8,2017-12-01,1,None,None,NaN,8,Thacher,Naseby,1993-07-17,941-527-3977,538 Mosinee Center,Sarasota,FL,205
3,4,2,2017-01-22,1,None,None,NaN,2,Ines,Brushfield,1986-04-13,804-427-9456,14187 Commercial Trail,Hampton,VA,947
4,5,5,2017-08-25,2,,2017-08-26,3.0,5,Clemmie,Betchley,1973-11-07,None,5 Spohn Circle,Arlington,TX,3675
5,6,10,2018-11-18,1,Aliquam erat volutpat. In congue.,None,NaN,10,Levy,Mynett,1969-10-13,404-246-3370,68 Lawn Avenue,Atlanta,GA,796
6,7,2,2018-09-22,2,None,2018-09-23,4.0,2,Ines,Brushfield,1986-04-13,804-427-9456,14187 Commercial Trail,Hampton,VA,947
7,8,5,2018-06-08,1,"Mauris enim leo, rhoncus sed, vestibulum sit a...",None,NaN,5,Clemmie,Betchley,1973-11-07,None,5 Spohn Circle,Arlington,TX,3675
8,9,10,2017-07-05,2,Nulla mollis molestie lorem. Quisque ut erat.,2017-07-06,1.0,10,Levy,Mynett,1969-10-13,404-246-3370,68 Lawn Avenue,Atlanta,GA,796
9,10,6,2018-04-22,2,None,2018-04-23,2.0,6,Elka,Twiddell,1991-09-04,312-480-8498,7 Manley Drive,Chicago,IL,3073

In [32]:
query = """
select order_id, orders.customer_id, first_name, last_name
from orders
join customers on orders.customer_id = customers.customer_id
"""

pd.read_sql(query, con= engine)

   order_id  customer_id first_name   last_name
0         4            2       Ines  Brushfield
1         7            2       Ines  Brushfield
2         5            5    Clemmie    Betchley
3         8            5    Clemmie    Betchley
4         1            6       Elka    Twiddell
5        10            6       Elka    Twiddell
6         2            7      Ilene      Dowson
7         3            8    Thacher      Naseby
8         6           10       Levy      Mynett
9         9           10       Levy      Mynett

we can give an ailias to each table to write cleaner code:

In [33]:
query = """
select order_id, o.customer_id, first_name, last_name
from orders o
join customers c 
    on o.customer_id = c.customer_id
"""

pd.read_sql(query, con= engine)

   order_id  customer_id first_name   last_name
0         4            2       Ines  Brushfield
1         7            2       Ines  Brushfield
2         5            5    Clemmie    Betchley
3         8            5    Clemmie    Betchley
4         1            6       Elka    Twiddell
5        10            6       Elka    Twiddell
6         2            7      Ilene      Dowson
7         3            8    Thacher      Naseby
8         6           10       Levy      Mynett
9         9           10       Levy      Mynett

EXERCISE:

In [34]:
query = """
select oi.order_id, oi.product_id, p.name, oi.quantity, oi.unit_price
from order_items oi
join products p
	on oi.product_id = p.product_id
"""

pd.read_sql(query, con= engine)

    order_id  product_id                          name  quantity  unit_price
0          2           1             Foam Dinner Plate         2        9.10
1          6           1             Foam Dinner Plate         4        8.65
2         10           1             Foam Dinner Plate        10        6.01
3          5           2     Pork - Bacon,back Peameal         3        9.89
4          6           2     Pork - Bacon,back Peameal         4        3.28
5          3           3      Lettuce - Romaine, Heart        10        9.12
6          4           3      Lettuce - Romaine, Heart         7        6.99
7          6           3      Lettuce - Romaine, Heart         4        7.46
8          7           3      Lettuce - Romaine, Heart         7        9.17
9          1           4  Brocolinni - Gaylan, Chinese         4        3.74
10         2           4  Brocolinni - Gaylan, Chinese         4        1.66
11         6           5        Sauce - Ranch Dressing         1        3.45
12         8           5        Sauce - Ranch Dressing         2        6.94
13         2           6                Petit Baguette         2        2.94
14         9           6                Petit Baguette         5        7.28
15         8           8      Island Oasis - Raspberry         2        8.59
16        10           9                        Longan         9        4.28
17         4          10                  Broom - Push         7        6.40

## Joining Across Databases
we can choose tables from different database to work with them

In [35]:
query = """
select oi.order_id, oi.product_id, p.name, oi.quantity, oi.unit_price
from order_items oi
join sql_inventory.products p
	on oi.product_id = p.product_id
"""
# note that we are in "sql_store" database but we add another table from "sql_inventory" database

pd.read_sql(query, con= engine)

    order_id  product_id                          name  quantity  unit_price
0          2           1             Foam Dinner Plate         2        9.10
1          6           1             Foam Dinner Plate         4        8.65
2         10           1             Foam Dinner Plate        10        6.01
3          5           2     Pork - Bacon,back Peameal         3        9.89
4          6           2     Pork - Bacon,back Peameal         4        3.28
5          3           3      Lettuce - Romaine, Heart        10        9.12
6          4           3      Lettuce - Romaine, Heart         7        6.99
7          6           3      Lettuce - Romaine, Heart         4        7.46
8          7           3      Lettuce - Romaine, Heart         7        9.17
9          1           4  Brocolinni - Gaylan, Chinese         4        3.74
10         2           4  Brocolinni - Gaylan, Chinese         4        1.66
11         6           5        Sauce - Ranch Dressing         1        3.45
12         8           5        Sauce - Ranch Dressing         2        6.94
13         2           6                Petit Baguette         2        2.94
14         9           6                Petit Baguette         5        7.28
15         8           8      Island Oasis - Raspberry         2        8.59
16        10           9                        Longan         9        4.28
17         4          10                  Broom - Push         7        6.40

## Self Joins

In [36]:
query = """
select 
    e.employee_id,
    e.first_name,
    m.first_name as manager
from sql_hr.employees e
join sql_hr.employees m
	on e.reports_to = m.employee_id
"""

pd.read_sql(query, con= engine)

    employee_id  first_name   manager
0         33391      D'arcy  Yovonnda
1         37851       Sayer  Yovonnda
2         40448       Mindy  Yovonnda
3         56274     Keriann  Yovonnda
4         63196     Alaster  Yovonnda
5         67009       North  Yovonnda
6         67370    Elladine  Yovonnda
7         68249       Nisse  Yovonnda
8         72540     Guthrey  Yovonnda
9         72913        Kass  Yovonnda
10        75900       Virge  Yovonnda
11        76196     Mirilla  Yovonnda
12        80529       Lynde  Yovonnda
13        80679     Mildrid  Yovonnda
14        84791       Hazel  Yovonnda
15        95213        Cole  Yovonnda
16        96513     Theresa  Yovonnda
17        98374  Estrellita  Yovonnda
18       115357         Ivy  Yovonnda

## Joining Multiple Tables

In [37]:
query = """
select 
	o.order_id,
    o.order_date,
    c.first_name,
    c.last_name,
    os.name as status
from orders o
join customers c
	on o.customer_id = c.customer_id
join order_statuses os
	on o.status = os.order_status_id
"""

pd.read_sql(query, con= engine)

   order_id  order_date first_name   last_name     status
0         8  2018-06-08    Clemmie    Betchley  Processed
1         6  2018-11-18       Levy      Mynett  Processed
2         4  2017-01-22       Ines  Brushfield  Processed
3         3  2017-12-01    Thacher      Naseby  Processed
4         1  2019-01-30       Elka    Twiddell  Processed
5        10  2018-04-22       Elka    Twiddell    Shipped
6         9  2017-07-05       Levy      Mynett    Shipped
7         7  2018-09-22       Ines  Brushfield    Shipped
8         5  2017-08-25    Clemmie    Betchley    Shipped
9         2  2018-08-02      Ilene      Dowson    Shipped

EXERCISE:

In [38]:
query = """
select 
	p.date,
    p.invoice_id,
    p.amount,
    c.name,
    pm.name as payment_method
from sql_invoicing.payments p
join sql_invoicing.payment_methods pm
	on p.payment_method = pm.payment_method_id
join sql_invoicing.clients c
	on p.client_id = c.client_id
"""

pd.read_sql(query, con= engine)

         date  invoice_id  amount         name payment_method
0  2019-02-12           2    8.18  Topiclounge    Credit Card
1  2019-01-03           6   74.55        Vinte    Credit Card
2  2019-01-11          11    0.03        Yadel    Credit Card
3  2019-01-26          13   87.44  Topiclounge    Credit Card
4  2019-01-15          15   80.31        Yadel    Credit Card
5  2019-01-15          17   68.10        Yadel    Credit Card
6  2019-01-08          18   32.77  Topiclounge    Credit Card
7  2019-01-08          18   10.00  Topiclounge           Cash

## Compound Join Condition

In [39]:
query = """
select *
from order_items oi
join order_item_notes oin
	on oi.order_id = oin.order_Id
    and oi.product_id = oin.product_id
"""

pd.read_sql(query, con= engine)

Empty DataFrame
Columns: [order_id, product_id, quantity, unit_price, note_id, order_Id, product_id, note]
Index: []

## Outer Joins
`OUTER JOIN` in SQL returns rows even when there is no matching row in the other table. The unmatched columns are filled with NULL

Use cases: when you need all records from one table (or both tables with `FULL OUTER JOIN`), not only the intersecting matches—e.g., finding customers with or without orders.

In [40]:
query = """
select p.product_id, p.name, oi.quantity
from products p
left join order_items oi 
	on p.product_id = oi.product_id
"""

pd.read_sql(query, con= engine)

    product_id                          name  quantity
0            1             Foam Dinner Plate       2.0
1            1             Foam Dinner Plate       4.0
2            1             Foam Dinner Plate      10.0
3            2     Pork - Bacon,back Peameal       3.0
4            2     Pork - Bacon,back Peameal       4.0
5            3      Lettuce - Romaine, Heart      10.0
6            3      Lettuce - Romaine, Heart       7.0
7            3      Lettuce - Romaine, Heart       4.0
8            3      Lettuce - Romaine, Heart       7.0
9            4  Brocolinni - Gaylan, Chinese       4.0
10           4  Brocolinni - Gaylan, Chinese       4.0
11           5        Sauce - Ranch Dressing       1.0
12           5        Sauce - Ranch Dressing       2.0
13           6                Petit Baguette       2.0
14           6                Petit Baguette       5.0
15           7             Sweet Pea Sprouts       NaN
16           8      Island Oasis - Raspberry       2.0
17           9                        Longan       9.0
18          10                  Broom - Push       7.0

this code is same as above but as a best practice avoid using `RIGHT JOIN`:

In [41]:
query = """
select p.product_id, p.name, oi.quantity
from order_items oi
right join products p 
	on p.product_id = oi.product_id
"""

pd.read_sql(query, con= engine)

    product_id                          name  quantity
0            1             Foam Dinner Plate       2.0
1            1             Foam Dinner Plate       4.0
2            1             Foam Dinner Plate      10.0
3            2     Pork - Bacon,back Peameal       3.0
4            2     Pork - Bacon,back Peameal       4.0
5            3      Lettuce - Romaine, Heart      10.0
6            3      Lettuce - Romaine, Heart       7.0
7            3      Lettuce - Romaine, Heart       4.0
8            3      Lettuce - Romaine, Heart       7.0
9            4  Brocolinni - Gaylan, Chinese       4.0
10           4  Brocolinni - Gaylan, Chinese       4.0
11           5        Sauce - Ranch Dressing       1.0
12           5        Sauce - Ranch Dressing       2.0
13           6                Petit Baguette       2.0
14           6                Petit Baguette       5.0
15           7             Sweet Pea Sprouts       NaN
16           8      Island Oasis - Raspberry       2.0
17           9                        Longan       9.0
18          10                  Broom - Push       7.0

## Outer Joins Between Multiple Tables

In [42]:
query = """
select 
    o.order_id,
	o.order_date, 
    c.first_name,
    sh.name as shipper,
    os.name as status

from orders o

left join customers c
	on o.customer_id = c.customer_id

left join shippers sh
	on o.shipper_id = sh.shipper_id

join order_statuses os
	on o.status = os.order_status_id
    """

pd.read_sql(query, con= engine)

   order_id  order_date first_name                 shipper     status
0         8  2018-06-08    Clemmie                    None  Processed
1         6  2018-11-18       Levy                    None  Processed
2         4  2017-01-22       Ines                    None  Processed
3         3  2017-12-01    Thacher                    None  Processed
4         1  2019-01-30       Elka                    None  Processed
5        10  2018-04-22       Elka       Schinner-Predovic    Shipped
6         9  2017-07-05       Levy           Hettinger LLC    Shipped
7         7  2018-09-22       Ines  Mraz, Renner and Nolan    Shipped
8         5  2017-08-25    Clemmie         Satterfield LLC    Shipped
9         2  2018-08-02      Ilene  Mraz, Renner and Nolan    Shipped

### USING
this keyword is only available in MYSQL and POSTGRESQL

In [43]:
query = """
select p.product_id, p.name, oi.quantity
from order_items oi
right join products p 
--	on p.product_id = oi.product_id
    using(product_id)
"""

pd.read_sql(query, con= engine)

    product_id                          name  quantity
0            1             Foam Dinner Plate       2.0
1            1             Foam Dinner Plate       4.0
2            1             Foam Dinner Plate      10.0
3            2     Pork - Bacon,back Peameal       3.0
4            2     Pork - Bacon,back Peameal       4.0
5            3      Lettuce - Romaine, Heart      10.0
6            3      Lettuce - Romaine, Heart       7.0
7            3      Lettuce - Romaine, Heart       4.0
8            3      Lettuce - Romaine, Heart       7.0
9            4  Brocolinni - Gaylan, Chinese       4.0
10           4  Brocolinni - Gaylan, Chinese       4.0
11           5        Sauce - Ranch Dressing       1.0
12           5        Sauce - Ranch Dressing       2.0
13           6                Petit Baguette       2.0
14           6                Petit Baguette       5.0
15           7             Sweet Pea Sprouts       NaN
16           8      Island Oasis - Raspberry       2.0
17           9                        Longan       9.0
18          10                  Broom - Push       7.0

EXERCISE:

In [44]:
query = """
select 
	p.date,
	c.name as client,
    p.amount,
    pm.name as payment_method
from sql_invoicing.payments p
join sql_invoicing.clients c 
	using(client_id)
join sql_invoicing.payment_methods pm
	on p.payment_method = pm.payment_method_id
"""

pd.read_sql(query, con= engine)

         date       client  amount payment_method
0  2019-02-12  Topiclounge    8.18    Credit Card
1  2019-01-03        Vinte   74.55    Credit Card
2  2019-01-11        Yadel    0.03    Credit Card
3  2019-01-26  Topiclounge   87.44    Credit Card
4  2019-01-15        Yadel   80.31    Credit Card
5  2019-01-15        Yadel   68.10    Credit Card
6  2019-01-08  Topiclounge   32.77    Credit Card
7  2019-01-08  Topiclounge   10.00           Cash

## UNIONS

In [45]:
query = """
select 
	order_id,
    order_date,
    "Active" as status
from orders
where order_date >= "2019-01-01"
union
select 
	order_id,
    order_date,
    "Archived" as status
from orders
where order_date <= "2019-01-01"

"""

pd.read_sql(query, con= engine)

   order_id  order_date    status
0         1  2019-01-30    Active
1         2  2018-08-02  Archived
2         3  2017-12-01  Archived
3         4  2017-01-22  Archived
4         5  2017-08-25  Archived
5         6  2018-11-18  Archived
6         7  2018-09-22  Archived
7         8  2018-06-08  Archived
8         9  2017-07-05  Archived
9        10  2018-04-22  Archived

EXERCISE:

In [46]:
query = """
select 
	customer_id,
    first_name,
    points,
    "GOLD" as type
from customers
where points > 3000

union

select 
	customer_id,
    first_name,
    points,
    "SILVER"
from customers
where points between 2000 and 3000

union

select 
	customer_id,
    first_name,
    points,
    "BRONZE" as type
from customers
where points < 2000
"""

pd.read_sql(query, con= engine)

   customer_id first_name  points    type
0            5    Clemmie    3675    GOLD
1            6       Elka    3073    GOLD
2            1     Babara    2273  SILVER
3            3     Freddi    2967  SILVER
4            2       Ines     947  BRONZE
5            4      Ambur     457  BRONZE
6            7      Ilene    1672  BRONZE
7            8    Thacher     205  BRONZE
8            9     Romola    1486  BRONZE
9           10       Levy     796  BRONZE